import scrape
from tqdm import tqdm
import random
import time
import browser

def main():
  message = ["Please checkout our new generative art Spectrum by @LibertasART, if you like it you can have one on opensea: https://opensea.io/collection/libertasart",
             "https://opensea.io/collection/libertasart Checkout this new generative art Spectrum by @LibertasART, if you like it you can have one on opensea!", 
             "Come check out our generative art https://opensea.io/collection/libertasart",
             "Don't miss out this new generative art Spectrum by @LibertasART https://opensea.io/collection/libertasart",
             "Mirage of colors and shapes from @LibertasART https://twitter.com/LibertasART/status/1519836128936931328",
             "Here is our black streams by @LibertasART https://twitter.com/LibertasART/status/1516900653410439168",
             "Getting RED from @LibertasART https://twitter.com/LibertasART/status/1515679136794165254",
             "A thousand eyes look into your soul @LibertasART https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/85767881087532313767549472071991921861841406249621836330435394728130928181249",
             "Look at the Beauty generated by AI @LibertasART https://twitter.com/LibertasART/status/1513349835876974595",
             "Darkness is what the true world looks like by @LibertasART https://twitter.com/LibertasART/status/1511960674339074051",
             "Check out out new generative experiment https://twitter.com/LibertasART/status/1506889579080536066",
             "Feeling like Kooning https://twitter.com/LibertasART/status/1496506886140710922",
             "Check out out amazing work Colorful Scales on @opensea https://twitter.com/LibertasART/status/1522224910487195648",
             "Our Beauty https://twitter.com/LibertasART/status/1513349835876974595",
             "Here is one of our amazing work piece https://twitter.com/LibertasART/status/1501211638741016579",
            ]
  while True:
    sleepTime = random.randrange(1800, 3600, 30)
    messageNum = random.randrange(0,14,1)
    scrape.getTargetTweets('drop%20your%20nft')
    browser.reply(message[messageNum])
    for i in tqdm(range(sleepTime), desc="Waiting time: "):
      time.sleep(1)

main()
